Melt
Pivot
Aggregation
Iteration
Groupby

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp
import sklearn.model_selection as ms
import sklearn.utils as su
from sklearn import metrics
from tables.table import Col
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [19]:
data = pd.read_csv('/content/sample_data/diabetic_data.csv')
train = np.matrix(data[:70000])
test = np.matrix(data[70001:])
#test = test.values
#train = train.values
test = test[:,1:]
data=data[:10]

In [25]:
#melt
data.melt(id_vars='age', value_vars='[20-30)')

        age    variable value
0    [0-10)  readmitted    NO
1   [10-20)  readmitted   >30
2   [20-30)  readmitted    NO
3   [30-40)  readmitted    NO
4   [40-50)  readmitted    NO
5   [50-60)  readmitted   >30
6   [60-70)  readmitted    NO
7   [70-80)  readmitted   >30
8   [80-90)  readmitted    NO
9  [90-100)  readmitted    NO

In [21]:
#Pivot
p = data.pivot(index='patient_nbr', columns='gender', values='age')
p

gender         Female     Male
patient_nbr
8222157        [0-10)      NaN
42519267          NaN  [40-50)
48330783      [80-90)      NaN
55629189      [10-20)      NaN
63555939     [90-100)      NaN
82442376          NaN  [30-40)
82637451          NaN  [50-60)
84259809          NaN  [60-70)
86047875      [20-30)      NaN
114882984         NaN  [70-80)

In [27]:
#Aggregation
print(data.agg([np.mean, np.std, np.min, np.sum]))

      encounter_id   patient_nbr  \
mean  3.192660e+05  6.685278e+07
std   7.037738e+05  2.977717e+07
amin  1.252200e+04  8.222157e+06
sum   3.192660e+06  6.685278e+08

                                                   race  \
mean                                                NaN
std                                                 NaN
amin                                    AfricanAmerican
sum   CaucasianCaucasianAfricanAmericanCaucasianCauc...

                                                 gender  \
mean                                                NaN
std                                                 NaN
amin                                             Female
sum   FemaleFemaleFemaleMaleMaleMaleMaleMaleFemaleFe...

                                                    age      weight  \
mean                                                NaN         NaN
std                                                 NaN         NaN
amin                                             [0-10)           ?
sum   [0-10)[10-20)[20-30)[30-40)[40-50)[50-60)[60-7...  ??????????

      admission_type_id  discharge_disposition_id  admission_source_id  \
mean           2.100000                  3.600000             4.800000
std            1.595131                  7.545418             2.485514
amin           1.000000                  1.000000             1.000000
sum           21.000000                 36.000000            48.000000

      time_in_hospital  ...           citoglipton  \
mean          4.600000  ...                   NaN
std           4.351245  ...                   NaN
amin          1.000000  ...                    No
sum          46.000000  ...  NoNoNoNoNoNoNoNoNoNo

                                       insulin   glyburide-metformin  \
mean                                       NaN                   NaN
std                                        NaN                   NaN
amin                                        No                    No
sum   NoUpNoUpSteadySteadySteadyNoSteadySteady  NoNoNoNoNoNoNoNoNoNo

       glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
mean                   NaN                       NaN                      NaN
std                    NaN                       NaN                      NaN
amin                    No                        No                       No
sum   NoNoNoNoNoNoNoNoNoNo      NoNoNoNoNoNoNoNoNoNo     NoNoNoNoNoNoNoNoNoNo

      metformin-pioglitazone                change  \
mean                     NaN                   NaN
std                      NaN                   NaN
amin                      No                    Ch
sum     NoNoNoNoNoNoNoNoNoNo  NoChNoChChNoChNoChCh

                        diabetesMed               readmitted
mean                            NaN                      NaN
std                             NaN                      NaN
amin                             No                      >30
sum   NoYesYesYesYesYesYesYesYesYes  NO>30NONONO>30NO>30NONO

[4 rows x 50 columns]

In [30]:
#Iteration
for row_index,row in data.iterrows():
    print(row_index,row)

0 encounter_id                                 2278392
patient_nbr                                  8222157
race                                       Caucasian
gender                                        Female
age                                           [0-10)
weight                                             ?
admission_type_id                                  6
discharge_disposition_id                          25
admission_source_id                                1
time_in_hospital                                   1
payer_code                                         ?
medical_specialty           Pediatrics-Endocrinology
num_lab_procedures                                41
num_procedures                                     0
num_medications                                    1
number_outpatient                                  0
number_emergency                                   0
number_inpatient                                   0
diag_1                                        250.83
diag_2                                             ?
diag_3                                             ?
number_diagnoses                                   1
max_glu_serum                                   None
A1Cresult                                       None
metformin                                         No
repaglinide                                       No
nateglinide                                       No
chlorpropamide                                    No
glimepiride                                       No
acetohexamide                                     No
glipizide                                         No
glyburide                                         No
tolbutamide                                       No
pioglitazone                                      No
rosiglitazone                                     No
acarbose                                          No
miglitol                                          No
troglitazone                                      No
tolazamide                                        No
examide                                           No
citoglipton                                       No
insulin                                           No
glyburide-metformin                               No
glipizide-metformin                               No
glimepiride-pioglitazone                          No
metformin-rosiglitazone                           No
metformin-pioglitazone                            No
change                                            No
diabetesMed                                       No
readmitted                                        NO
Name: 0, dtype: object
1 encounter_id                   149190
patient_nbr                  55629189
race                        Caucasian
gender                         Female
age                           [10-20)
weight                              ?
admission_type_id                   1
discharge_disposition_id            1
admission_source_id                 7
time_in_hospital                    3
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 59
num_procedures                      0
num_medications                    18
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            276
diag_2                         250.01
diag_3                            255
number_diagnoses                    9
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                          No
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                            Up
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                        >30
Name: 1, dtype: object
2 encounter_id                          64410
patient_nbr                        86047875
race                        AfricanAmerican
gender                               Female
age                                 [20-30)
weight                                    ?
admission_type_id                         1
discharge_disposition_id                  1
admission_source_id                       7
time_in_hospital                          2
payer_code                                ?
medical_specialty                         ?
num_lab_procedures                       11
num_procedures                            5
num_medications                          13
number_outpatient                         2
number_emergency                          0
number_inpatient                          1
diag_1                                  648
diag_2                                  250
diag_3                                  V27
number_diagnoses                          6
max_glu_serum                          None
A1Cresult                              None
metformin                                No
repaglinide                              No
nateglinide                              No
chlorpropamide                           No
glimepiride                              No
acetohexamide                            No
glipizide                            Steady
glyburide                                No
tolbutamide                              No
pioglitazone                             No
rosiglitazone                            No
acarbose                                 No
miglitol                                 No
troglitazone                             No
tolazamide                               No
examide                                  No
citoglipton                              No
insulin                                  No
glyburide-metformin                      No
glipizide-metformin                      No
glimepiride-pioglitazone                 No
metformin-rosiglitazone                  No
metformin-pioglitazone                   No
change                                   No
diabetesMed                             Yes
readmitted                               NO
Name: 2, dtype: object
3 encounter_id                   500364
patient_nbr                  82442376
race                        Caucasian
gender                           Male
age                           [30-40)
weight                              ?
admission_type_id                   1
discharge_disposition_id            1
admission_source_id                 7
time_in_hospital                    2
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 44
num_procedures                      1
num_medications                    16
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                              8
diag_2                         250.43
diag_3                            403
number_diagnoses                    7
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                          No
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                            Up
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                         NO
Name: 3, dtype: object
4 encounter_id                    16680
patient_nbr                  42519267
race                        Caucasian
gender                           Male
age                           [40-50)
weight                              ?
admission_type_id                   1
discharge_disposition_id            1
admission_source_id                 7
time_in_hospital                    1
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 51
num_procedures                      0
num_medications                     8
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            197
diag_2                            157
diag_3                            250
number_diagnoses                    5
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                      Steady
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                        Steady
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                         NO
Name: 4, dtype: object
5 encounter_id                    35754
patient_nbr                  82637451
race                        Caucasian
gender                           Male
age                           [50-60)
weight                              ?
admission_type_id                   2
discharge_disposition_id            1
admission_source_id                 2
time_in_hospital                    3
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 31
num_procedures                      6
num_medications                    16
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            414
diag_2                            411
diag_3                            250
number_diagnoses                    9
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                          No
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                        Steady
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             No
diabetesMed                       Yes
readmitted                        >30
Name: 5, dtype: object
6 encounter_id                    55842
patient_nbr                  84259809
race                        Caucasian
gender                           Male
age                           [60-70)
weight                              ?
admission_type_id                   3
discharge_disposition_id            1
admission_source_id                 2
time_in_hospital                    4
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 70
num_procedures                      1
num_medications                    21
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            414
diag_2                            411
diag_3                            V45
number_diagnoses                    7
max_glu_serum                    None
A1Cresult                        None
metformin                      Steady
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                    Steady
acetohexamide                      No
glipizide                          No
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                        Steady
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                         NO
Name: 6, dtype: object
7 encounter_id                    63768
patient_nbr                 114882984
race                        Caucasian
gender                           Male
age                           [70-80)
weight                              ?
admission_type_id                   1
discharge_disposition_id            1
admission_source_id                 7
time_in_hospital                    5
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 73
num_procedures                      0
num_medications                    12
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            428
diag_2                            492
diag_3                            250
number_diagnoses                    8
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                          No
glyburide                      Steady
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                            No
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             No
diabetesMed                       Yes
readmitted                        >30
Name: 7, dtype: object
8 encounter_id                    12522
patient_nbr                  48330783
race                        Caucasian
gender                         Female
age                           [80-90)
weight                              ?
admission_type_id                   2
discharge_disposition_id            1
admission_source_id                 4
time_in_hospital                   13
payer_code                          ?
medical_specialty                   ?
num_lab_procedures                 68
num_procedures                      2
num_medications                    28
number_outpatient                   0
number_emergency                    0
number_inpatient                    0
diag_1                            398
diag_2                            427
diag_3                             38
number_diagnoses                    8
max_glu_serum                    None
A1Cresult                        None
metformin                          No
repaglinide                        No
nateglinide                        No
chlorpropamide                     No
glimepiride                        No
acetohexamide                      No
glipizide                      Steady
glyburide                          No
tolbutamide                        No
pioglitazone                       No
rosiglitazone                      No
acarbose                           No
miglitol                           No
troglitazone                       No
tolazamide                         No
examide                            No
citoglipton                        No
insulin                        Steady
glyburide-metformin                No
glipizide-metformin                No
glimepiride-pioglitazone           No
metformin-rosiglitazone            No
metformin-pioglitazone             No
change                             Ch
diabetesMed                       Yes
readmitted                         NO
Name: 8, dtype: object
9 encounter_id                           15738
patient_nbr                         63555939
race                               Caucasian
gender                                Female
age                                 [90-100)
weight                                     ?
admission_type_id                          3
discharge_disposition_id                   3
admission_source_id                        4
time_in_hospital                          12
payer_code                                 ?
medical_specialty           InternalMedicine
num_lab_procedures                        33
num_procedures                             3
num_medications                           18
number_outpatient                          0
number_emergency                           0
number_inpatient                           0
diag_1                                   434
diag_2                                   198
diag_3                                   486
number_diagnoses                           8
max_glu_serum                           None
A1Cresult                               None
metformin                                 No
repaglinide                               No
nateglinide                               No
chlorpropamide                            No
glimepiride                               No
acetohexamide                             No
glipizide                                 No
glyburide                                 No
tolbutamide                               No
pioglitazone                              No
rosiglitazone                         Steady
acarbose                                  No

In [36]:
#Groupby
gb = data.groupby(['gender', 'age'])
gb.first()

                 encounter_id  patient_nbr             race weight  \
gender age
Female [0-10)         2278392      8222157        Caucasian      ?
       [10-20)         149190     55629189        Caucasian      ?
       [20-30)          64410     86047875  AfricanAmerican      ?
       [80-90)          12522     48330783        Caucasian      ?
       [90-100)         15738     63555939        Caucasian      ?
Male   [30-40)         500364     82442376        Caucasian      ?
       [40-50)          16680     42519267        Caucasian      ?
       [50-60)          35754     82637451        Caucasian      ?
       [60-70)          55842     84259809        Caucasian      ?
       [70-80)          63768    114882984        Caucasian      ?

                 admission_type_id  discharge_disposition_id  \
gender age
Female [0-10)                    6                        25
       [10-20)                   1                         1
       [20-30)                   1                         1
       [80-90)                   2                         1
       [90-100)                  3                         3
Male   [30-40)                   1                         1
       [40-50)                   1                         1
       [50-60)                   2                         1
       [60-70)                   3                         1
       [70-80)                   1                         1

                 admission_source_id  time_in_hospital payer_code  \
gender age
Female [0-10)                      1                 1          ?
       [10-20)                     7                 3          ?
       [20-30)                     7                 2          ?
       [80-90)                     4                13          ?
       [90-100)                    4                12          ?
Male   [30-40)                     7                 2          ?
       [40-50)                     7                 1          ?
       [50-60)                     2                 3          ?
       [60-70)                     2                 4          ?
       [70-80)                     7                 5          ?

                        medical_specialty  ...  citoglipton  insulin  \
gender age                                 ...
Female [0-10)    Pediatrics-Endocrinology  ...           No       No
       [10-20)                          ?  ...           No       Up
       [20-30)                          ?  ...           No       No
       [80-90)                          ?  ...           No   Steady
       [90-100)          InternalMedicine  ...           No   Steady
Male   [30-40)                          ?  ...           No       Up
       [40-50)                          ?  ...           No   Steady
       [50-60)                          ?  ...           No   Steady
       [60-70)                          ?  ...           No   Steady
       [70-80)                          ?  ...           No       No

                 glyburide-metformin  glipizide-metformin  \
gender age
Female [0-10)                     No                   No
       [10-20)                    No                   No
       [20-30)                    No                   No
       [80-90)                    No                   No
       [90-100)                   No                   No
Male   [30-40)                    No                   No
       [40-50)                    No                   No
       [50-60)                    No                   No
       [60-70)                    No                   No
       [70-80)                    No                   No

                 glimepiride-pioglitazone  metformin-rosiglitazone  \
gender age
Female [0-10)                          No                       No
       [10-20)                         No                       No
       [20-30)                         No                       No
       [80-90)                         No                       No
       [90-100)                        No                       No
Male   [30-40)                         No                       No
       [40-50)                         No                       No
       [50-60)                         No                       No
       [60-70)                         No                       No
       [70-80)                         No                       No

                metformin-pioglitazone change diabetesMed  readmitted
gender age
Female [0-10)                       No     No          No          NO
       [10-20)                      No     Ch         Yes         >30
       [20-30)                      No     No         Yes          NO
       [80-90)                      No     Ch         Yes          NO
       [90-100)                     No     Ch         Yes          NO
Male   [30-40)                      No     Ch         Yes          NO
       [40-50)                      No     Ch         Yes          NO
       [50-60)                      No     No         Yes         >30
       [60-70)                      No     Ch         Yes          NO
       [70-80)                      No     No         Yes         >30

[10 rows x 48 columns]